import jsonlines
import os
import json
from functools import cmp_to_key

BRANDS = os.listdir("data/raw/brand_with_models")

rule all:
    input:
        "data/processed/pledges_ner.xls"

rule create_dictionary:
    input:
        expand("data/raw/brand_with_models/{brand}", brand=BRANDS),
    output:
        "data/interim/dictionary_brand_model.jsonl",
    run: 
        dictionary = {}
        for file in input:
            with open(file, 'r') as outfile:
                data = json.load(outfile)
                name = data['id']
                dictionary[name] = data
        with open(output[0], 'w') as outfile:
            json_string = json.dumps(dictionary)
            outfile.write(json_string)

rule create_rules:
    input:
        "data/interim/dictionary_brand_model.jsonl"
    output:
        "data/interim/rules.jsonl"
    shell:
        "python src/data/prepare_rules.py {input} {output}"

rule create_important_names:
    input:
        "data/interim/dictionary_brand_model.jsonl",
        "data/raw/important_add_name.jsonl",
        "data/raw/important_remove_name.jsonl",
    output:
        "data/interim/important_names.jsonl"
    shell:
        "python src/data/prepare_important_names.py {input} {output}"

rule add_ner:
    input:
        "data/raw/pledges.xlsx",
        "data/interim/rules.jsonl",
        "data/interim/important_names.jsonl"
    output:
        "data/processed/pledges_ner.xls"
    shell:
        "python src/models/find_NER.py {input} {output}"